### ISSUE TITLE
Patch does not apply

### ISSUE THREAD

**Issue by reeseschultz** [AndreaCatania/godex#14]
### Problem

Following the [Compiling wiki page](https://github.com/AndreaCatania/godex/wiki/Compiling) with Godot at [this commit](https://github.com/godotengine/godot/commit/36c943260ed40c6e31a6ecff7f6e1674714b4fcb) and Godex at [this commit](https://github.com/AndreaCatania/godex/commit/2d3db4c4129dabb18bfaf509b4e98322b655af8f), I ran `git apply modules/godex/patches/add_custom_iterator.patch`.

That resulted in this error:

```sh
error: patch failed: core/config/engine.h:88
error: core/config/engine.h: patch does not apply
error: patch failed: main/main.cpp:2497
error: main/main.cpp: patch does not apply
```
### Workaround

I can successfully apply the patch after checking out a previous—albeit recent—commit of Godot like so:

```sh
git checkout 2e66e5d5992a521fe27dc88fee92c680f4adf98b
```

Understandably Godot's master branch is hectic, so the patch will inevitably fall out of sync until [this PR](https://github.com/godotengine/godot/pull/42875) is merged. It's probably kind of annoying to maintain the patch. If it helps, I'd be happy to update Godex's wiki by mentioning that last-known compatible Godot commit.

**Edit:** Actually, I had to make a some minor changes to Godex for Godot to compile with it. I'm wondering, which commit of Godot is safest to use with Godex? I want to avoid recompiling a bunch of times.

**Comment by AndreaCatania** [comment]
I can updated that patch, the idea is to stay up to date with Godot master, though, I think it's a good idea to say which godot commit is tested on. I'm going to update the wiki and provide a new patch.

It would be welcome if you could support this proposal https://github.com/godotengine/godot-proposals/issues/1592, so we would not need to maintain this patch much longer.

I'll submit a new PR to godot, with the current patch that is smarter than this https://github.com/godotengine/godot/pull/42875

**Comment by AndreaCatania** [comment]
Done, I've added the tested commit number on the [READ.me](https://github.com/AndreaCatania/godex/blob/main/README.md) and the [wiki](https://github.com/AndreaCatania/godex/wiki/Compiling)

**Comment by AndreaCatania** [comment]
I've also updated the PR code, here: https://github.com/godotengine/godot/pull/42875 to reflect the current godox's patch.

**Comment by reeseschultz** [comment]
Thank you very much!
