### ISSUE TITLE
Adding or selecting a WorldECS node eliminates greater Godot window context

### ISSUE THREAD

**Issue by reeseschultz** [AndreaCatania/godex#18]
https://user-images.githubusercontent.com/43183393/103444937-ff9a0f00-4c3b-11eb-8baa-d5d18563e400.mp4

This seems to be a new bug. Previously, I recall the WorldECS window being treated as a sub-window, but now it is treated as the whole window and everything else disappears. I'm not sure if there's some button I'm missing that will take me back.

The Godot build in question uses Godex 114646e and the recommended commit of Godot from the README. I'm happy to provide any other information if requested.

**Comment by AndreaCatania** [comment]
That's interesting, probably some new flag should be used, I'll give it a check.

**Comment by AndreaCatania** [comment]
Probably a regression of https://github.com/godotengine/godot/commit/8a2bc6bf58e305a55ae7b54b8eeafa435575c744

**Comment by AndreaCatania** [comment]
Fixed with #19.
